<!-- Badges: -->
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg?logo=paypal&style=flat-square)](https://www.paypal.me/CamponogaraViera/100)
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/QuCAI-Lab/ibm2021-open-science-prize/blob/dev/simulation.ipynb)
[![License](https://img.shields.io/github/license/QuCAI-Lab/ibm2021-open-science-prize.svg?logo=CreativeCommons&style=flat-square)](https://github.com/QuCAI-Lab/ibm2021-open-science-prize/blob/dev/LICENSE.md)
[![Contributions](https://img.shields.io/badge/contributions-welcome-orange?style=flat-square)](https://github.com/QuCAI-Lab/ibm2021-open-science-prize/pulls)
[![Maintenance](https://img.shields.io/badge/Maintained%3F-yes-green.svg)](https://github.com/QuCAI-Lab/ibm2021-open-science-prize/graphs/commit-activity)
[![Release](https://img.shields.io/github/release/QuCAI-Lab/ibm2021-open-science-prize.svg)](https://github.com/QuCAI-Lab/ibm2021-open-science-prize/releases)

<div align="center">
  <h1> <a target="_blank" href="https://research.ibm.com/blog/quantum-open-science-prize" rel="noopener noreferrer">2021 IBM Open Science Prize</a>  </h1>
  <h1><b> Supplementary Material </b></h1>
  <h3><b> Simulating the XXX Heisenberg Model Hamiltonian for a System of Three Interacting Spin-1/2 Particles on IBM Quantum’s 7-qubit Jakarta Processor </b></h3>
</div>
<br> 

<!-- Author: -->
<div align="center">
<b>Developer: <a target="_blank" href="https://github.com/camponogaraviera"> ¹Lucas Camponogara Viera</a></b>
<br>   
<b><a target="_blank" href="https://en.ntnu.edu.tw/" rel="noopener noreferrer">¹National Taiwan Normal University - NTNU, Taipei, Taiwan</a></b>.
</div>

<br>

<table class="tfo-notebook-buttons" align="head">
  <td>
    <a target="_blank" href="https://github.com/QuCAI-Lab/ibm2021-open-science-prize"><img src="https://www.tensorflow.org/images/GitHub-Mark-32px.png" /></a>
  </td>
</table>

In [1]:
%autosave 30

Autosaving every 30 seconds


---
In this Jupyter notebook, the reader will find algebraic derivations regarding the quantum simulation presented in the `simulation.ipynb` notebook file. The mathematical framework employed in the remainder of this Jupyter notebook is the contemporary matrix mechanics formalism of quantum mechanics initially developed by Werner Heisenberg, Max Born, and Pascual Jordan in a sequel of articles between 1925 and 1926. Within this formalism, the central pivots of the theory are the physical observables (e.g., spin, electric charge, magnetic flux, position, momentum, etc.) represented by Hermitian operators (self-adjoint matrices) where the corresponding eigenvectors form a set of orthonormal basis for the Hilbert space.

---

# Table of Contents

- **[Postulates of quantum mechanics](#postulates)**
  - Postulate 1 (State Space)
  - Postulate 2 (Evolution)
  - Postulate 3 (Measurement)
  - Postulate 4 (Composite State)
- **[System's Dynamics: Schrödinger equation](#dynamics)**
 - Wave Mechanics formalism
 - Matrix Mechanics formalism
- **[Solution for the Schrödinger equation](#solutions)**
- **[The Heisenberg XXX Spin-1/2 Lattice Model for  N=3  Three Particles](#model)**
- **[Time Evolution of the initial state $|110\rangle$ under $h_{heis3}$ according to $U_{\text{heis3}}(t=\pi)$](#evolution)**
  - Probability Over Time  t.
- **[The Trotter-Susuki formula](#trotter)**
- **[Decomposition of $U_{\text{Heis3}}(t)$ using Trotterization](#decomp)**
- **[Transpilation of $U_{\text{Heis3}}(t)$ Into Quantum Gates](#transp)**
  - The  e−itZZ  gate
  - The  e−itXX  gate
  - The  e−itYY  gate
- **[State Fidelity](#fid)**
- **[References](#ref)**



# &nbsp; <a href="https://creativecommons.org/licenses/by/4.0/"><img valign="middle" src="https://img.icons8.com/copyright" width="50"></a> License

In [ ]:
#@title Copyright 2022.
# This code is part of heisenberg-model.
#
# (C) Copyright NTNU QuCAI-Lab, 2022.
#
# This code is licensed under the Creative Commons Zero v1.0 Universal License. 
# You may obtain a copy of the License at https://github.com/QuCAI-Lab/ibm2021-open-science-prize/blob/dev/LICENSE.md.

# &nbsp; <a href="https://colab.research.google.com/"><img valign="middle" src="https://www.tensorflow.org/images/colab_logo_32px.png" width="50"></a> Pip Install

* **Run the following cells only if you are running this Jupyter notebook outside the [heisenberg_model environment](https://github.com/QuCAI-Lab/ibm2021-open-science-prize/blob/dev/environment.yml).**

Installing `Qiskit`, `NumPy`, and `pylatexenc`.

In [ ]:
'''
# Installing a non-default library

!python3 -m pip install <library_name>

# Alternative 

!apt-get -qq install -y <library_name> && python3 -m pip install -U <library_name> 

# Upgrading an installed library

!python3 -m pip install -U --upgrade <library_name> 
'''

'\n# Installing a non-default library\n\n!python3 -m pip install <library_name>\n\n# Alternative \n\n!apt-get -qq install -y <library_name> && python3 -m pip install -U <library_name> \n\n# Upgrading an installed library\n\n!python3 -m pip install -U --upgrade <library_name> \n'

In [ ]:
try:
  import pip, pkg_resources
  pkg_resources.require("pip>=21.1.3") # Latest version: 22.0.4
  print(pip.__version__)
except:
  import subprocess, sys
  cmd = "python3 -m pip install --upgrade pip"
  process = subprocess.Popen(cmd,shell=True,bufsize=1,stdout=subprocess.PIPE,
                             stderr=subprocess.STDOUT,encoding='utf-8',errors='replace') 
  while True:
    out = process.stdout.readline()
    if out == '' and process.poll() is not None:
      break
    if out:
      print(out.strip(), flush=False)
      sys.stdout.flush()
  #raise

21.1.3


In [ ]:
#!python3 -m pip install pip==version_number # To downgrade pip.
!pip --version

pip 21.1.3 from /usr/local/lib/python3.7/dist-packages/pip (python 3.7)


**NumPy:**

In [ ]:
!python3 -m pip install numpy==1.20.1

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


**Qiskit:**

In [ ]:
!python3 -m pip install qiskit==0.35.0

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


**pylatexenc**:

In [ ]:
# The 'pylatexenc' library is required to use 'MatplotlibDrawer'.

!python -m pip install pylatexenc==2.10

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


# &nbsp; <a href="#"><img valign="middle" height="45px" src="https://img.icons8.com/python" width="45" hspace="0px" vspace="0px"></a> Dependencies

- Importing modules.

In [3]:
import IPython
import qiskit
import numpy as np 
from qiskit import QuantumCircuit
from qiskit.circuit import Parameter

In [ ]:
### If using Google Colab, one needs to restart Colab Runtime after pip install. ###

try:
  import pkg_resources, watermark
  pkg_resources.require("watermark>=2.3.0") # Force watermark version.
  print(watermark.__version__)
except:
  import subprocess, sys
  if "google.colab" in sys.modules:
    cmd = "python3 -m pip install --upgrade watermark" # Upgrade watermak.

    process = subprocess.Popen(cmd,shell=True,bufsize=1,stdout=subprocess.PIPE, \
                              stderr=subprocess.STDOUT,encoding='utf-8',errors='replace') 
    while True: 
      out = process.stdout.readline() # The first line of the file.
      if out == '' and process.poll() is not None: # Run the loop until condition is True.
        break 
      if out:
        print(out.strip(), flush=False) # Removes leading and trailing empty spaces. 
        sys.stdout.flush()
    #raise # To raise the import error. Upgrade will be successful regardless.

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
# If you get hit by the error "No module named watermark", run this cell twice!

#%load_ext watermark
%reload_ext watermark
%watermark -a 'LucasCamponogaraViera' -gu 'QuCAI-Lab' -ws 'https://github.com/QuCAI-Lab/ibm2021-open-science-prize' -w -u -d -v -m -iv

Author: LucasCamponogaraViera

Github username: QuCAI-Lab

Website: https://github.com/QuCAI-Lab/ibm2021-open-science-prize

Last updated: 2022-06-28

Python implementation: CPython
Python version       : 3.7.13
IPython version      : 5.5.0

Compiler    : GCC 7.5.0
OS          : Linux
Release     : 5.4.188+
Machine     : x86_64
Processor   : x86_64
CPU cores   : 2
Architecture: 64bit

IPython  : 5.5.0
watermark: 2.3.1
qiskit   : 0.35.0
pip      : 21.1.3
sys      : 3.7.13 (default, Apr 24 2022, 01:04:09) 
[GCC 7.5.0]
numpy    : 1.20.1

Watermark: 2.3.1



In [ ]:
print(IPython.sys_info())

{'commit_hash': 'b467d487e',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/usr/local/lib/python3.7/dist-packages/IPython',
 'ipython_version': '5.5.0',
 'os_name': 'posix',
 'platform': 'Linux-5.4.188+-x86_64-with-Ubuntu-18.04-bionic',
 'sys_executable': '/usr/bin/python3',
 'sys_platform': 'linux',
 'sys_version': '3.7.13 (default, Apr 24 2022, 01:04:09) \n[GCC 7.5.0]'}


# Postulates of quantum mechanics<a name="postulates" />  

- Matrix Mechanics formalism using Dirac bra-ket notation.

## **Postulate 1 (State Space)**


Any **isolated (close)** quantum system is completely described by a normalized *state vector* $|\psi\rangle$ which is a unit vector embedded in a complex vector space (Hilbert space) $\mathcal{H}$ known as the *state space* of the system endowed with an inner product $(\cdot,\cdot) \doteq \langle \cdot | \cdot \rangle$.

<br></br>

- **First case: Discrete Spectrum.**

When the spectrum of the eigenvalues are discrete, the state $|\psi\rangle$ of the quantum system is embedded in a Hilbert space $\mathcal{H}$ of dimension $d=\dim \mathcal{H}$. In a complete and discrete orthonormal basis $\{|o_j\rangle\}_{j=1}^d$, the state vector reads

\begin{eqnarray}
|\psi\rangle \doteq \sum_{j=1}^d c_j|o_j\rangle.
\end{eqnarray}

The inner product for orthonormal eigenstates becomes 

$$\langle o_j|o_k\rangle = \delta_{jk},$$

and the probability amplitude $c_j$ associated with the eigenstate $|o_j\rangle$ is obtained via the Fourier trick 

$$c_j=\langle o_j|\psi\rangle.$$ 

- **Second case: Continuous Spectrum.**

When the spectrum of the eigenvalues are continous, the state $|\psi\rangle$ of the quantum system is embedded in a infinite-dimensional Hilbert space $|\psi\rangle \in \mathcal{H}$  whose orthonormal basis $\{|q\rangle \}$ is formed by an uncountably infinite set of orthonormal vectors. In this particular case, the state of the quantum system in this basis reads:

\begin{eqnarray}
|\psi\rangle \doteq \int \psi_{q} |q\rangle d_{q},
\end{eqnarray}

which is a linear combination given in terms of an integral, rather than a sum (See Ref. [2], Section 3.2.3, pg. 103). The inner product thus becomes the Dirac delta distribution

\begin{eqnarray}
\langle q |q'\rangle  = \delta (q-q'), 
\end{eqnarray}

and the analogous Fourier trick gives the complex-valued scalar wave function $\psi_{q}$ as the probability amplitude:

\begin{eqnarray}
\psi_{q} = \langle q |\psi \rangle.
\end{eqnarray}

Note that $\psi_q$ is the standard wave function of the ubiquitous Schrodinger equation of wave mechanics, often denote by $\psi(q)$ or $\psi(x)$ if in the position space.

## **Postulate 2 (Evolution)**

The evolution of a **closed quantum system** over time is described by a *unitary transformation* given by the action of the propagator $\hat{U}_t\equiv\hat{U}(t)$ known as the Unitary time evolution operator. Therefore, the global state $|\psi_t\rangle$ of the system at time $t$ has evolved from the initial state $|\psi_0\rangle$ at time $t=0$ according to:

\begin{equation} 
|\psi_t\rangle=\hat{U}_t|\psi_0\rangle.
\end{equation}  

**Note:** in the particular case of closed systems, the evolution operator $\hat{U}_t$ of the system's global state $|\psi\rangle$ is Unitary, however, open quantum systems (systems interacting with its surroundings) described by mixed states, in general, have non-Unitary operators describing the evolution of its subsystems.







## **Postulate 3 (Measurement)**

Measurements of a quantum system are described by a collection \{$M_m$\} of *measurement operators* acting on the state space of the system with $m$ possible measurement outcomes. If the quantum system is prepared in a general state $|\psi\rangle$, the probability associated with a measurement outcome $o_m$ is:

\begin{equation} 
Pr(o_m)\doteq\langle \psi | M^{\dagger}_{m} M_{m} |\psi \rangle,
\end{equation} 

and the state of the system immediately after the measurement of the eigenvalue $o_m$ will be:

\begin{align} 
    |\psi_{o_m} \rangle= \frac{M_{m} |\psi \rangle}{\sqrt{\langle \psi | M^{\dagger}_{m} M_{m} |\psi \rangle}}. 
\end{align}

The measurement operators satisfy the completeness relation:

\begin{equation} 
\sum_{m} M_{m}^{\dagger} M_{m} = \mathbb{I},
\end{equation}

meaning that probabilities must sum to one, i.e, $|\psi\rangle$ is normalized:

\begin{equation} 
\sum_{m} Pr(o_m) = \sum_{m} \langle \psi | M^{\dagger}_{m} M_{m} |\psi \rangle = 1.
\end{equation}  

## **Postulate 4 (Composite State)**

Consider a quantum system composed of $N$ arbitrary subsystems, where subsystem $s$ is prepared in a qudit state $|\psi_{s}\rangle = \sum_{j=1}^{d_s} c_{j_s} |o_{j}\rangle_s$ embedded in a $d_s$-dimensional Hilbert space $\mathcal{H}_s^{d_s}$ with orthonormal basis $\{|o_{j}\rangle_s \}|_{j=1}^{d_s}$. The Hilbert state space $\mathcal{H}^{d}_{1\cdots N}$ of the composite physical system is given by the tensor product of its constituent Hilbert spaces (the state space of its subsystems or component physical systems): $\mathcal{H}^{d}_{1\cdots N}=\otimes_{s=1}^N \mathcal{H}_s^{d_s}=\mathcal{H}_1^{d_1} \otimes \mathcal{H}_2^{d_2} \otimes \cdots \otimes \mathcal{H}_N^{d_N}$, where $d=\prod_{s=1}^N d_s$ is the dimension of the composite space. And the corresponding orthonormal basis of the composite state space is obtained from the tensor product between the basis of each constituent state space: $\{|o_{j}\rangle \}|_{j=1}^{d}=\{|o_{j}\rangle_s \otimes \cdot\cdot\cdot \otimes|o_{k}\rangle_N \}|_{j,\cdots,k=1}^{d_s,\cdots,d_N}$. 

# System's dynamics: Schrödinger equation<a name="dynamics" />  

- **Wave Mechanics** and **Matrix Mechanics** formalisms.

## Wave Mechanics formalism


In the wave mechanics formalism of quantum mechanics, the dynamics of a system of particles is determined by the linear partial differential and time-dependent Schrödinger equation, which in the position representation reads:

\begin{eqnarray}
i \hbar \frac{\partial \Psi(\vec{r}, t)}{\partial t} &= \hat{H}(t)\Psi(\vec{r}, t).
\end{eqnarray}

Where: 

- $\Psi(\vec{r}, t) \doteq \Psi(x, y, z, t): \mathbb{R}^{4}\rightarrow\mathbb{C}$ is the complex valued scalar wavefunction containing the information about the particle's dynamics in the *position space* of continuous spectrum. The spectrum is the set of all eigenvalues of a given operator.
- $\hat{H}(t)$ is the Hamiltonian of the system, i.e, the sum of its kinetic and potential energy.
- $i$ is the imaginary unit.
- $\hbar$ is the reduced Planck constante a.k.a quantum of action.

The Schrödinger equation can also be written in the form:

\begin{eqnarray}
{i\hbar\partial_{t}\Psi(\vec{q},t)=\left(-\frac{\hbar^{2}}{2m} \nabla^{2}_{\vec{q}}+V(\vec{q},t) \right) \Psi(\vec{q},t)}.
\end{eqnarray}

Where:

- $\partial_t \equiv \frac{\partial}{\partial_t}$.
- $\nabla^2_{\vec{q}}$ is the second-order differential Laplace operator in generalized coordinates $q_j|_{j=1}^3$. 
- $V(\vec{q}, t)$ is the time-dependent potential energy.

The Laplace operator is defined as the divergence ($\vec{\nabla} \cdot $) of the gradient ($\vec{\nabla} \Phi$) and, therefore, it is a scalar operator and contrasts with the gradient which is a vector operator acting on a scalar field (function) $\Phi$. 

- The gradient operator in **generalized coordinates**. Given a scalar field $\Phi=\Phi(q_1, q_2, q_3)$,

$$\vec{\nabla}_{\vec{q}} \Phi = \frac{\partial \Phi}{h_j\partial q_j} \hat{e}_j =  \frac{1}{h_1}\frac{\partial \Phi}{\partial q_1} \hat{e}_1 + \frac{1}{h_2}\frac{\partial \Phi}{\partial q_2} \hat{e}_2 + \frac{1}{h_3}\frac{\partial \Phi}{\partial q_3} \hat{e}_3.$$

- The divergence operator in **generalized coordinates**. Given a vectorial field $\vec{A}=A(q_1, q_2, q_3)= A_1 \hat{e}_1+A_2 \hat{e}_2+A_3 \hat{e}_3$,

$$\vec{\nabla}_{\vec{q}} \cdot \vec{A} =  \frac{1}{h_1 h_2 h_3} \bigg[\frac{\partial (A_1 h_2 h_3)}{\partial q_1} + \frac{\partial (A_2 h_1 h_3)}{\partial q_2} + \frac{\partial (A_3 h_1 h_2)}{\partial q_3} \bigg].$$


- The Laplace operator in **Cartesian coordinates**. Given a scalar field $\Phi=\Phi(x, y, z)$,

$$\nabla^2_{\vec{r}} \Phi = \vec{\nabla} \cdot \vec{\nabla}(\Phi) = \partial_{rr} \Phi = \sum_{j=1}^3\frac{\partial^2 \Phi}{\partial r_j^2} = \frac{\partial^2 \Phi}{\partial x^2}+ \frac{\partial^2 \Phi}{\partial y^2} + \frac{\partial^2 \Phi}{\partial z^2}.$$

## Matrix Mechanics formalism


In the Hilbert state space (statevector) formalism (a.k.a qubit representation), the time-dependent Schrödinger equation reads:

\begin{eqnarray}
i \hbar\frac{d}{dt}|\psi(t)\rangle= \hat{H} |\psi(t)\rangle,
\end{eqnarray}

where $|\psi\rangle$ is the state of the quantum system in a linear superposition (combination) according to definitions for either a continuous or a discrete case as provided in the section `"Postulates of quantum mechanics"`.


### Schrödinger Picture (S-P)

In the **Schrödinger picture** (S-P) (representation), the evolution of the initial state $|\psi_{t=0}^S\rangle\equiv|\psi(t=0)\rangle$ over a time $t$ is given by:

\begin{equation} 
|\psi_t^S\rangle=\hat{U}_t|\psi_0^S\rangle. \tag{1}
\end{equation}  

While the operator describing a certain physical observable remains constant in time:

\begin{equation} 
\hat{O}_t^S=\hat{O}_0^S=\sum_{j=1}^d o_j |o_j^S\rangle\langle o_j^S|. \tag{2}
\end{equation}  

### Heisenberg Picture (H-P)

In the **Heisenberg picture** (H-P), the operator describing a certain physical observable evolves over a time $t$ according to:

\begin{eqnarray} 
\hat{O}_t^H &=& \sum_{j=1}^d o_j |o_j^H (t)\rangle\langle o_j^H (t)| = \sum_{j=1}^d o_j \hat{U}_{t}^{\dagger}|o_j^S\rangle\langle o_j^S|\hat{U}_t = \hat{U}_t^{\dagger}\sum_{j=1}^d o_j|o_j^S\rangle\langle o_j^S|\hat{U}_t \\
&=& \hat{U}_t^{\dagger} \hat{O}_0^S \hat{U}_t.
\end{eqnarray} 

where

\begin{equation} 
|o_j^H(t)\rangle = \hat{U}_t^{\dagger}|o_j^S\rangle. \tag{3}
\end{equation}  

While the global state $|\psi\rangle$ of the quantum system remains constant:

\begin{equation} 
|\psi_t^H\rangle = |\psi_0^S\rangle. \tag{4}
\end{equation}  

Regardless of the picture used, H-P or S-P, solution for $\hat{U}_t$ is obtained solving the Schrödinger equation of the time evolution operator:

\begin{equation} 
i\hbar \partial_t \hat{U}_t = \hat{H}_t\hat{U}_t. \tag{5}
\end{equation}  

From equations (1) and (5), one can verify the equivalent Schrödinger equation for the quantum state, as follows:

\begin{equation} 
i\hbar \partial_t |\psi_t\rangle = i\hbar \partial_t (\hat{U}_t |\psi_0\rangle) = (i\hbar \partial_t \hat{U}_t)|\psi_0\rangle = \hat{H}_t \hat{U}_t|\psi_0\rangle= \hat{H}_t|\psi_t\rangle. \tag{6}
\end{equation}  

Where:
- $\partial_t \equiv \frac{\partial}{\partial_t}$.

# Solution for the Schrödinger equation<a name="solutions" />  

- Matrix exponentiation.

Solution for the Schrödinger equation of the time-dependent evolution operator $\hat{U}(t)$ depends mostly on the characteristic of the Hamiltonian $\hat{H}$. In the matrix mechanics formalism, the Sch. eq. in the S-P writes

\begin{equation} 
i\hbar \frac{d}{dt}(\hat{U}(t) |\psi(0)\rangle)=\hat{H}(t) (\hat{U}(t) |\psi(0)\rangle).
\end{equation}  

One then has:

\begin{equation} 
 \frac{d}{dt} \hat{U}(t) = \frac{-i}{\hbar}\hat{H}\hat{U}(t).
\end{equation}  

A know fact from linear algebra is that any Unitary operator can be constructed by means of some Hermitian operator and a real number $\gamma$:

\begin{eqnarray}
\hat{U}=e^{-i\gamma\hat{H}}.
\end{eqnarray}

To show the above is true, one can prove its unitarity:

\begin{eqnarray}
\hat{U}^{\dagger}&=&(e^{-i\gamma\hat{H}})^{\dagger}=e^{i\gamma\hat{H}^{\dagger}} = e^{i\gamma\hat{H}}, \\
&\implies&
\hat{U}\hat{U}^{\dagger}=e^{-i\gamma\hat{H}}e^{i\gamma\hat{H}}=\mathbb{I},
\end{eqnarray}

where it was used the property: $(e^{z\hat{A}})^{\dagger} = e^{(z\hat{A})^{\dagger}}=e^{\hat{A}^{\dagger}z^{\dagger}}=e^{z^{\dagger}\hat{A}^{\dagger}}$, for a complex number $z$ and matrix $\hat{A}$.

In the particular case of a **time-independent Hamiltonian (conservative system)**, the above relation can be used to write the closed-form solution as:

\begin{eqnarray}
\hat{U}(t) = e^{-i\hat{H}t / \hbar}.
\end{eqnarray}

One can check this result by expanding the exponential function in Taylor series around the point $x_0=0$ (Maclaurin series) and differentiating term by term. The Maclauring series for $f(x)=e^{i\gamma\hat{H}}$ with $e^{\mathbb{O}}=\mathbb{I}$ is:

\begin{eqnarray}
e^{i\gamma\hat{H}} = \sum_{n=0}^{\infty} \frac{({i\gamma\hat{H}})^n}{n!} = \mathbb{I}+i\gamma \hat{H}+\frac{(i\gamma \hat{H})^2}{2}+\frac{(i\gamma \hat{H})^3}{3!}+\cdots +\frac{(i\gamma \hat{H})^n}{n!}.
\end{eqnarray}

So that for $\gamma=-t/\hbar$:

\begin{eqnarray}
\frac{d}{dt} (e^{-i\hat{H}t / \hbar})&=&\frac{d}{dt} \left( \mathbb{I} - i\hat{H}t/\hbar - \frac{\hat{H}^2 t^2}{2\hbar^2}  + \cdots + \frac{(-i\hat{H}t)^n}{n!\hbar^n}\right)  \\
&=& \left(0 -i\hat{H}/\hbar - \frac{\hat{H}^2t}{\hbar^2} + \cdots + \frac{n(-i\hat{H})^nt^{n-1}}{n!\hbar^n}\right), \\
&=&  \frac{-i}{\hbar}\hat{H} \left(\mathbb{I} - \frac{i\hat{H}t}{\hbar} + \cdots + \frac{(-i\hat{H})^{n-1}t^{n-1}}{(n-1)!\hbar^{n-1}}\right), \text{ defining } k \equiv n-1\\
\\
&=&  \frac{-i}{\hbar}\hat{H} \left(\mathbb{I} - \frac{i\hat{H}t}{\hbar} + \cdots + \frac{(-i\hat{H}t)^{k}}{k!\hbar^{k}}\right)\\
&=& \frac{-i}{\hbar}\hat{H}e^{-i\hat{H}t / \hbar},
\end{eqnarray}

where it was used: $\frac{n}{n!}=\frac{n}{n(n-1)!}=\frac{1}{(n-1)!}$.

Note that for $\hat{H}=\sum_{j}^n \hat{H}_j$, in general, $[\hat{H}_j, \hat{H}_k] \neq 0$, and thus $e^{-i\hat{H} \cdot t} \neq \prod_j e^{-i\hat{H}_j \cdot t}$. That is to say:

$$e^{-i\hat{H}t} = e^{-i\hat{H}_1\cdot t} \cdot e^{-i\hat{H}_2\cdot t} \cdots e^{-i\hat{H}_n\cdot t} \text{ iff } [\hat{H}_j, \hat{H}_k]=0.$$

Another way of looking at the problem of solving differential equations is to consider the first order approximation (see Ref. [1], Sec. 4.7.2):

\begin{eqnarray}
|\psi(t+\Delta t)\rangle &\approx& |\psi(t)\rangle + \Delta t \frac{d}{dt} |\psi(t)\rangle\\
&=& (\mathbb{I}-\frac{i}{\hbar}\hat{H}\Delta t)|\psi(t)\rangle.
\end{eqnarray} 

The approximation to high order can be obtained considering small time evolutions ($t<<1$):

\begin{eqnarray}
|\psi(t)\rangle &\approx& (\mathbb{I}-\frac{i}{\hbar}\hat{H} t)|\psi(0)\rangle \\
&=& (\mathbb{I}-\frac{i t}{2\hbar}\hat{H} )(\mathbb{I}-\frac{it}{2\hbar}\hat{H})|\psi(0)\rangle.
\end{eqnarray} 

Such that 
\begin{eqnarray}
|\psi(t)\rangle &=& lim_{N\rightarrow \infty} (\mathbb{I}-\frac{it}{N\hbar}\hat{H})^N|\psi(0)\rangle \\ 
&=& e^{-i\hat{H}t/\hbar} |\psi(0)\rangle.
\end{eqnarray} 

Where it was used: $e^{\hat{A}} = lim_{N\rightarrow \infty} (\mathbb{I}+ \frac{\hat{A}}{N})^N$.

# The Heisenberg XXX Spin-1/2 Lattice Model for $N=3$ Three Particles<a name="model" />  


The [Quantum Heisenberg XXX spin-1/2 model](https://en.wikipedia.org/wiki/Quantum_Heisenberg_model#XXX_model) is a particular case of the general [XYZ Quantum Heisenberg Model](https://en.wikipedia.org/wiki/Quantum_Heisenberg_model) when the coupling coefficients are $J_x = J_y = J_z \doteq J$. The particle interaction of the aforementioned spin model for a system of $N$ quantum spin-1/2 particles arranged in a 1D (one-dimensional) Markov chain, where each particle is represented by a qubit, is given by the following `Hamiltonian operator`:

\begin{eqnarray}
h_{\text{heis}} &=& \sum_{\langle jk \rangle =0}^{N-1} J \left(\sigma_x^{(j)} \otimes \sigma_x^{(k)} + \sigma_y^{(j)} \otimes \sigma_y^{(k)} + \sigma_z^{(j)} \otimes \sigma_z^{(k)}\right).
\end{eqnarray}
Where: 
- $J$ is a real-valued [coupling](https://en.m.wikipedia.org/wiki/Coupling_constant) constant that determines the interaction strength.
- $\langle jk \rangle$ specifies interaction only between nearest neighbor qubits $j$ and $k$ ($j,k \in \{0,1,2\}$).
- $\otimes$ denotes the [Kronecker product](https://en.wikipedia.org/wiki/Kronecker_product) symbol between two matrices.

<br></br>
In classical mechanics, the Hamiltonian $H$ corresponds to the sum of kinetic and potential energy of a **time-independent holonomic and monogenic system** \[Goldstein, H.]. In quantum mechanics, the Hamiltonian is promoted to a so-called Hermitian operator $\hat{H}$ represented by a self-adjoint complex matrix within the matrix mechanics formalism.

The Pauli operators in this 1D spin lattice satisfy the following Lie algebra for the (anti-)commutation relations:


\begin{eqnarray}
\text{commutator: } \{\sigma_a^{j}, \sigma_b^{k} \} = 2\delta_{jk}\delta_{ab}\sigma_0^{j},\\
\end{eqnarray}
\begin{eqnarray}
\text{anti-commutator: }
[\sigma_a^{j}, \sigma_b^{k}] = 2i\delta_{jk}\epsilon_{abc}\sigma_c^{j}.
\end{eqnarray}

Where

- $[\hat{A},\hat{B}]$ denotes the bilinear skew-symmetric map $[,]: \mathcal{g} x \mathcal{g} \rightarrow \mathcal{g}$ (a.k.a commutator) between operators $\hat{A}$ and $\hat{B}$:

\begin{align}
[\hat{A},\hat{B}]\doteq\hat{A}\hat{B} - \hat{B}\hat{A}.
\end{align}
- $i=\sqrt{-1}$ denotes the imaginary unit.
- $\epsilon_{abc}$ denotes the normalized Levi-Civita symbol ($\epsilon_{xyz}=1$) with $a, b, c \in \{x,y,z\}$:

\begin{align*}
\varepsilon_{abc} \doteq
\begin{cases}
+1 & \text{for even permutation of }(a,b,c). \\
-1 & \text{for odd permutation of } (a,b,c).  \\
\;\;\,0 & \text{for any repeated index}.
\end{cases}
\end{align*}

- $\delta_{jk}$ denotes the Kronecker delta:

\begin{eqnarray}
\delta_{jk} \doteq \begin{cases}
0, & \mbox{if } j \ne k, \\
1, & \mbox{if } j=k. \end{cases}
\end{eqnarray}
- $\{\sigma_x,\sigma_y,\sigma_z\}$ denotes the $SU(2)$ set of [Pauli operators](https://en.wikipedia.org/wiki/Pauli_matrices) (2x2 complex Hermitian and Unitary matrices sharing equal eigenvalues of $\pm 1$).

For the particular case of a system of $N=3$ spin-1/2 particles arranged in a line, and setting $J=1$, one then has:

\begin{eqnarray}
h_{\text{heis}} &=& \sigma_x^{(0)}\otimes\sigma_x^{(1)}\otimes \mathbb{I}^{(2)} + \mathbb{I}^{(0)} \otimes\sigma_x^{(1)}\otimes\sigma_x^{(2)} + \sigma_y^{(0)}\otimes\sigma_y^{(1)}\otimes \mathbb{I}^{(2)} + \mathbb{I}^{(0)} \otimes \sigma_y^{(1)}\otimes\sigma_y^{(2)} + \mathbb{I}^{(0)} \otimes\sigma_z^{(0)}\otimes\sigma_z^{(1)} + \mathbb{I}^{(0)}\otimes\sigma_z^{(1)}\otimes\sigma_z^{(2)}.
\end{eqnarray}

However, the convention adopted by the quantum community is the following shorthand notation (omitting the Kronecker product ($\otimes$) and the 2x2 identity matrix $\mathbb{I}$):

\begin{eqnarray}
h_{\text{heis3}} = \sigma_x^{(0)}\sigma_x^{(1)} + \sigma_x^{(1)}\sigma_x^{(2)} + \sigma_y^{(0)}\sigma_y^{(1)} + \sigma_y^{(1)}\sigma_y^{(2)} + \sigma_z^{(0)}\sigma_z^{(1)} + \sigma_z^{(1)}\sigma_z^{(2)}.
\end{eqnarray}

# Time Evolution of the initial state $|110\rangle$ under $h_{heis3}$ according to $U_{\text{heis3}}(t=\pi)$<a name="evolution" />  


To see how the state of the quantum system envolves from the initial state $|110\rangle$ to the final state $U_{\text{Heis3}}(t=\pi)|110\rangle = |\psi(\pi)\rangle$ with probability $|\langle 110 | U_{\text{Heis3}}(\pi) |110\rangle|^2$, one should recall the first and second postulates of quantum mechanics in the ubiquitous Dirac bra-ket notation.

## **Probability Over Time $t$**

Consider a physical observable, which is always represented by a Hermitian ($\hat{\mathcal{O}}=\hat{\mathcal{O}}^{\dagger}$) and, therefore, Normal ($ \hat{\mathcal{O}}\hat{\mathcal{O}}^{\dagger}=\hat{\mathcal{O}}^{\dagger}\hat{\mathcal{O}}$) operator with real eigenvalues $o_j$. A diagonal representation (See the spectral decomposition theorem) in terms of the outer product representation can be given by:
\begin{eqnarray}
\hat{\mathcal{O}} = \sum_{j=1}^d o_j P_{o_j}= \sum_{j=1}^d o_j |o_j\rangle \langle o_j|.
\end{eqnarray}

Where $P_{o_j}=|o_j\rangle \langle o_j|$ is the projector onto the eigenspace of the observable $\hat{\mathcal{O}}$ in some $d$-dimensional orthonormal basis $\{|o_j \rangle\}|_{j=1}^d$ with an orthonormal set of eigenvectors $|o_j \rangle$ ($\langle o_j|o_k\rangle=\delta_{jk}$).

If the quantum system is prepared in the state $|\psi\rangle \doteq \sum_{j=1}^d c_j|o_j\rangle$, a projective measurement (a.k.a von Neumann measurement) entails the following conditional probability for finding the system in the eigenstate $|o_j\rangle$ with eigenvalue $o_j$:

\begin{eqnarray} 
Pr(o_j|\psi\rangle)&=&\langle \psi | P^{\dagger}_{o_j} P_{o_j} |\psi \rangle \\ 
&=& \langle \psi | P_{o_j}^2 |\psi \rangle\\
&=& \langle \psi| (|o_j\rangle \langle o_j|o_j\rangle \langle o_j|)| \psi \rangle\\
&=&\delta_{jj}\langle\psi|o_j\rangle \langle o_j |\psi\rangle \\ 
&=& |\langle \psi|o_j \rangle|^2=|\langle o_j|\psi \rangle|^2\\
&=& \left|\langle o_j|\sum_{k=1}^d c_k |o_k\rangle\right|^2\\
&=&  \left|\sum_{k=1}^d c_k \langle o_j|o_k\rangle\right|^2\\
&=&\left|\sum_{k=1}^d c_k \delta_{jk} \right|^2 = |c_j|^2.
\end{eqnarray} 

This result is also known as Born's rule:

\begin{eqnarray}
Pr(|o_j\rangle) \doteq |\langle o_j |\psi \rangle|^2 = |c_j|^2.
\end{eqnarray}

<br></br>
If the system has evolved from the initial state $|\psi(0)\rangle$ to the final state $|\psi(t)\rangle$, then:

\begin{eqnarray}
P_t(|o_j\rangle) &=& |\langle o_j | \hat{U}(t) |\psi(0)\rangle|^2 \\
&=& |\langle o_j |\psi(t)\rangle|^2.
\end{eqnarray}

Therefore, the probability of measuring the initial state $|\psi(0)\rangle=|110\rangle$ over a time window $t=\pi$ under the **time-independent Hamiltonian** XXX Heisemberg Hamiltonian is:

\begin{eqnarray}
P_{t=\pi}(|110\rangle) &=& |\langle 110 | u_{heis3}(t=\pi) |110\rangle|^2 \\
&=& |\langle 110 |e^{-ih_{heis3}\pi / \hbar} |110\rangle|^2.
\end{eqnarray}

Q.E.D.

This last equation is known as the transition probability. It resembles the modulus squared of the expectation value of an observable $\hat{O}$ as in $|\langle \hat{O}\rangle|^2$. **However, the evolution operator is not a Hermitian operator and, therefore, it does not describe a physical observable.** Expected value only makes sense for physical observables!

The expectation value of a physical observable $\hat{\mathcal{O}}$ is:

\begin{align}
\langle \hat{\mathcal{O}}\rangle &=\sum_{j=1}^d o_j Pr(o_j|\psi\rangle) \\
&=\sum_{j=1}^d o_j  \langle \psi |o_j \rangle \langle o_j|\psi \rangle \\
&= \langle \psi | \left(\sum_{j=1}^d o_j |o_j \rangle \langle o_j| \right) |\psi \rangle\\
&= \langle \psi | \left(\sum_{j=1}^d o_j P_{o_j} \right) |\psi \rangle\\
&=\langle \psi |\hat{\mathcal{O}}|\psi\rangle.
\end{align}

Upon evolution of the system's state vector ($\hat{U}(t)|\psi\rangle$), the expected value becomes:

\begin{align}
\langle \psi |U^{\dagger}\hat{\mathcal{O}}\hat{U}|\psi\rangle.
\end{align}

# The Trotter-Susuki formula<a name="trotter" />  

Consider the following decomposition for a general Hamiltonian $\hat{H}$:

\begin{align}
\hat{H} = \hat{H}_a + \hat{H}_b.
\end{align}

If the reduced Hamiltonians commute, i.e, $[\hat{H}_{a},\hat{H}_{b}]=\mathbb{O}$, then the evolution operator is a product of reduced evolution operators:

\begin{align}
\hat{U} = e^{-i\hat{H}t/ħ} = e^{-i\hat{H}_{a}t/\hbar-i\hat{H}_{b}t/\hbar} = e^{-i\hat{H}_{a}t/\hbar}e^{-i\hat{H}_{b}t/\hbar} = \hat{U}_{a}\hat{U}_{b} = \hat{U}_{b}\hat{U}_{a}.
\end{align}






In the case where $[H_a^{(0,1)},H_b^{(1,2)}]\ne\mathbb{O}$, one cannot simply write the evolution operator $\hat{U}$ as a product of evolution operators, therefore, another method must be adopted. There are several techniques to approximate a time Unitary evolution $\hat{U}=e^{-i\hat{H}t/\hbar}$ into gate operations for quantum simulation, to name a few:

1. Trotter-Susuki formula.
2. Randomized evolution (Qdrift, density matrix exponentiation).
3. Linear combination of unitaries.
4. Quantum Walks (Qubitization).



The Lie product formula (a.k.a Trotter-Susuki formula) is defined as (setting $\hbar\equiv1$):

\begin{align}
U_{Trotter}(t) = e^{-it\Big(\hat{H}_a + \hat{H}_b\Big)} \equiv \lim_{N\rightarrow\infty}\Big(e^{-it \hat{H}_a/N}e^{-it \hat{H}_b /N}\Big)^{N}.
\end{align}

Advantages of using Trotterization:

- The algorithm is ancilla-free.

- It leverages the commutative property of the component Hamiltonians to achieve efficient simulation.

- It preserves the locality property of some unidimensional systems with nearest neighbor interactions enabling quantum simulation speed up.







The outline of the Trotterization algorithm a.k.a as product-formula method or splitting method is as follows:

**1.** Write the Hamiltonian operator $\hat{H}$ of the system of interest in the form:

\begin{eqnarray}
\hat{H}= \sum_{\gamma=1}^{\Gamma} \hat{H}_{\gamma},
\end{eqnarray}
where $\hat{H}_{\gamma}$ is itself a Hermitian operator.

**2.** Write the unitary evolution operator $U$ in terms of product of exponentials using the first-order Lie-Trotter formula defined as:

\begin{eqnarray}
\mathcal{L}_1(t) = e^{-it \hat{H}_{1}} \cdots e^{-it \hat{H}_{\Gamma}} = e^{-it \hat{H}} + O(t^2),
\end{eqnarray}
where $O(t^2)$ is the trotter error.

**3.** Perform $e^{-it\hat{H}}$ up to some error $\epsilon$ according to the spectral norm:

\begin{eqnarray}
||\hat{U}-e^{-it\hat{H}}|| \leq \epsilon.
\end{eqnarray}

**4.** Define the total cost of the simulation as:
\begin{eqnarray}
\text{total cost} = \text{no. of steps } \times \text{ cost}/\text{step}.
\end{eqnarray}

In step 3, each exponential in the evolution operator $U_{\text{Heis3}}(t)$ is transpiled into a quantum gate.

# Decomposition of $U_{\text{Heis3}}(t)$ using Trotterization<a name="decomp" />  

Consider the following decomposition for the Hamiltonian $H_{heis3}$:

\begin{align}
H_{heis3} = H_a^{(0,1)} + H_b^{(1,2)},
\end{align}
where
\begin{align}
H_a^{(0,1)}  =\big(X^{(0)} \otimes X^{(1)} + Y^{(0)}\otimes Y^{(1)} + Z^{(0)}\otimes Z^{(1)}\big)\otimes \mathbb{I}^{(2)}, \\
H_b^{(1,2)} = \mathbb{I}^{(0)}\otimes \big(X^{(1)}\otimes X^{(2)} +  Y^{(1)}\otimes Y^{(2)} + Z^{(1)}\otimes Z^{(2)}\big),
\end{align}

We note that the pair of operators in the exponential of $U_{Trotter}(t)$ commute, i.e,

$$[X\otimes X,Y\otimes Y] = [X\otimes X,Z\otimes Z] = [Y\otimes Y,Z\otimes Z] =\mathbb{O}.$$

One can verify this is true, as follows ($j\ne k$):

\begin{eqnarray}
[\sigma_{j}\otimes\sigma_{j},\sigma_{k}\otimes\sigma_{k}] & = (\sigma_{j}\otimes\sigma_{j}) \cdot (\sigma_{k}\otimes\sigma_{k}) - (\sigma_{k}\otimes\sigma_{k}) \cdot (\sigma_{j}\otimes\sigma_{j}),
\end{eqnarray}

using $(A\otimes B)\cdot(C\otimes D)=AC\otimes BD$, one then has

\begin{eqnarray}
[\sigma_{j}\otimes\sigma_{j},\sigma_{k}\otimes\sigma_{k}]=\sigma_{j}\sigma_{k}\otimes\sigma_{j}\sigma_{k} - \sigma_{k}\sigma_{j}\otimes\sigma_{k}\sigma_{j} 
\end{eqnarray}

and given the $\mathfrak{su}(2)$ Lie algebra $\sigma_{j}\sigma_{k} = \sigma_{0}\delta_{jk}+i\epsilon_{jkl}\sigma_{l}$, it becomes

\begin{eqnarray}
[\sigma_{j}\otimes\sigma_{j},\sigma_{k}\otimes\sigma_{k}]&=& i\epsilon_{jkl}\sigma_{l}\otimes i\epsilon_{jkl}\sigma_{l} -i\epsilon_{kjl}\sigma_{l}\otimes i\epsilon_{kjl}\sigma_{l} \\
&=& i^{2}\epsilon_{jkl}^{2}\sigma_{l}\otimes\sigma_{l} -i^{2}\epsilon_{kjl}^{2}\sigma_{l}\otimes \sigma_{l} \\
&=& i^{2}\epsilon_{jkl}^{2}\sigma_{l}\otimes\sigma_{l} -i^{2}(-\epsilon_{jkl})^{2}\sigma_{l}\otimes \sigma_{l} \\
&=& \mathbb{O}.
\end{eqnarray}


With the above result in hands, the exponential $e^{-itH_a^{01}} $ can be written in the form:

\begin{eqnarray}
e^{-itH_a^{01}} &=& e^{-it(X\otimes X+ Y\otimes Y + Z\otimes Z)\otimes \mathbb{I}} \\ 
&=& e^{-it(X\otimes X\otimes \mathbb{I} + Y\otimes Y\otimes \mathbb{I} + Z\otimes Z\otimes \mathbb{I})} \\
&=& e^{-itX\otimes X\otimes \mathbb{I}}e^{-itY\otimes Y\otimes \mathbb{I}}e^{-itZ\otimes Z\otimes \mathbb{I}},
\end{eqnarray}

which after using $e^{A\otimes \mathbb{I}} = e^{A}\otimes \mathbb{I}$ becomes

\begin{eqnarray}
e^{-itH_a^{01}}&=& \Big(e^{-itX\otimes X}\otimes \mathbb{I}\Big)\Big(e^{-itY\otimes Y}\otimes \mathbb{I}\Big)\Big(e^{-itZ\otimes Z}\otimes \mathbb{I}\Big), \\
&=& \Big(e^{-itX\otimes X}\Big)\Big(e^{-itY\otimes Y}\Big)\Big(e^{-itZ\otimes Z}\Big)\otimes \mathbb{I}.
\end{eqnarray}

And equivalenty for $e^{-itH_b^{12}}$:

\begin{eqnarray}
e^{-itH_b^{12}} &= \mathbb{I}\otimes\Big( e^{-itX\otimes X}\Big)\Big( e^{-itY\otimes Y}\Big)\Big( e^{-itZ\otimes Z}\Big).
\end{eqnarray}

The unitary evolution operator for the decomposition of $H_{heis3}$ according to the Trotter-Suzuki fomula thus becomes:

\begin{eqnarray}
U_{\text{Heis3}}(t) &=& e^{-itH_{heis3}} = e^{-it\Big(H_a^{(0,1)} + H_b^{(1,2)}\Big)} = \lim_{N\rightarrow\infty}\Big(e^{-it H_a^{(0,1)}/N}e^{-it H_b^{(1,2)} /N}\Big)^{N}\\
&=& \lim_{N\rightarrow\infty}\left(\Big(e^{-it X^0\otimes X^1/N}e^{-it Y^0\otimes Y^1/N}e^{-it Z^0\otimes Z^1/N}\otimes \mathbb{I}\Big)\Big(\mathbb{I}\otimes e^{-it X^1\otimes X^2/N}e^{-it Y^1\otimes Y^2/N}e^{-it Z^1 \otimes Z^2/N}\Big)\right)^{N}.
\end{eqnarray}

Making the definitions

\begin{eqnarray}
XX(2t)^{(j,k)}\equiv e^{-it X^j \otimes X^k}, \\
YY(2t)^{(j,k)}\equiv e^{-it Y^j \otimes Y^k}, \\
ZZ(2t)^{(j,k)}\equiv e^{-it Z^j \otimes Z^k},
\end{eqnarray}

one then has:

\begin{eqnarray}
U_{\text{Heis3}}(t) = \lim_{N\rightarrow\infty}\Big[\Big(XX(2t/N)^{(0,1)}YY(2t/N)^{(0,1)}ZZ(2t/N)^{(0,1)}\otimes \mathbb{I}\Big)\Big(\mathbb{I}\otimes XX(2t/N)^{(1,2)}YY(2t/N)^{(1,2)}ZZ(2t/N)^{(1,2)}\Big)\Big]^{N}.
\end{eqnarray}

# Transpilation of $U_{\text{Heis3}}(t)$ Into Quantum Gates<a name="transp" />  

To build quantum circuits corresponding to unitary evolution operators from exponentials of the form $U=e^{-i\hat{H}\Delta t}$, one can use the parity trick (see Ref. [[1](#ref1)], Sec. 4.7.3). In the following sections, the quantum circuits provided by IBMQ are verified.

For a Hamiltonian of the form $\hat{H}=\sum_j^N \hat{H}_j = \sum_j^N \lambda P_j \otimes P_j$, with Pauli operators $P_j \in \{X, Y, Z\}$ and constant $\lambda$, transpilation into quantum gates of each one of the components can be achieved with the following steps (adapted from [[6](#ref6)]):

**1) Diagonalize the component Hamiltonian $\hat{H}_j=\lambda P_j \otimes P_j$:**

$$ \lambda (R_\hat{n}\otimes R_\hat{n}) e^{-itZ\otimes Z} (R_\hat{n} \otimes R_\hat{n}),$$ 

where $R_{\hat{n}} \in \{R_x, R_y, R_z \}$ is a local rotation (one-qubit gate) around the $\hat{n}$-axis.

**2) Compute the eigenvalues/parity information (phase shift) in the $|ij\rangle$ basis (usually implemented with CNOT gates):**

$$(Z \otimes Z)|ij\rangle = (-1)^{i \oplus j }|ij\rangle,$$ 

where $\oplus$ denotes the exclusive-OR symbol that represents the "direct sum" in mathematics and the parity in quantum mechanics.

**3) Compute the gate that kicks back the right parity (phase) information:**

$$e^{-i\lambda(-1)^{i\oplus j}\: Zt}.$$

**4) Uncompute the parity information. This is done by applying the Hermitian conjugate of the gate used to compute the parity.**

## The $e^{-itZZ}$ gate

The $e^{-itZZ}$ gate (a.k.a [RZZ](https://qiskit.org/documentation/stubs/qiskit.circuit.library.RZZGate.html)(2t)) has the following representation:

\begin{equation}
R_{zz}(2t)= \exp(-it Z\otimes Z)=cos\left(t\right)(\mathbb{I}_2\otimes \mathbb{I}_2)-isin\left(t\right)(Z\otimes Z).
\end{equation}

IBM supplementary material provides the following quantum circuit for the $e^{-itZZ}$ gate:

In [ ]:
# e^{(-itZZ)}

'''
from qiskit import QuantumCircuit
from qiskit.circuit import Parameter
'''

t = Parameter('t')
qc = QuantumCircuit(2)
qc.cnot(0,1)
qc.rz(2 * t, 1)
qc.cnot(0,1)
#qc.draw(output='mpl') # Requires 'pip install pylatexenc' library to use 'MatplotlibDrawer'.
qc.draw()

q_0: ──■───────────────■──
     ┌─┴─┐┌─────────┐┌─┴─┐
q_1: ┤ X ├┤ Rz(2*t) ├┤ X ├
     └───┘└─────────┘└───┘

The above circuit can be obtained using the parity trick, where the first CNOT gate computes the parity, and the second CNOT gate uncomputes the operation, since the CNOT (or CX) gate is both Unitary and Hermitian operator ($CX \cdot CX = CX \cdot CX^{\dagger} = \mathbb{I}$).

**Verification:**

**1)** This gate is already diagonalized in the Z-basis. 

To see this is true, recall from the spectral decomposition theorem for Normal matrices that any Normal operator $\hat{O}$ in a Hilbert space $\mathcal{H}$ of dimension $\dim \mathcal{H} =d$ is unitarily diagonalizable and has a spectral (eigenvalue) decomposition in terms of the outer product representation, and in the basis of its eigenvectors, of the form:

$$ \hat{O} = \sum_{j=1}^{d}= o_j P_{o_j} = \sum_{j=1}^{d} o_j |o_j \rangle \langle o_j|.$$

Where:

- $o_j$ and $P_{o_j}$ are the corresponding eigenvalue and projector operator of the observable $\hat{O}$, respectively. 

- $\{o_j\}|_{j=1}^d$ is a basis set of $d$ linearly independent orthonormal eigenvectors $|o_j\rangle$ of $\hat{O}$ with eigenvalue $o_j$.

Note that:

$$ \Bigg( \sum_{j=1}^{d} o_j |o_j \rangle \langle o_j| \Bigg) |o_k \rangle =  \sum_{j=1}^{d} o_j |o_j \rangle \delta_{jk}= o_k |o_k \rangle = \hat{O} |o_k \rangle.$$

Since Pauli operators are all involutory operators, i.e, their eigenvalues are $o_j = \pm 1$, one then has 

$$Z=|0\rangle\langle 0|-|1\rangle\langle 1|.$$

**2)** Computing the parity information by acting with the $ZZ$ operator:

\begin{eqnarray}
ZZ|00\rangle &=& |00\rangle, \\
ZZ|10\rangle &=& -|10\rangle, \\
ZZ|01\rangle &=& -|01\rangle, \\
ZZ|11\rangle &=& |11\rangle. \\
\end{eqnarray}

One can see that a minus sign (phase) is introduced whenever the basis state has odd parity (01 or 10). Therefore, in the computational basis, a phase shift will be applied to the system according to $e^{i\Delta t}$ if the parity of the $n$ qubits in the computational basis is odd, otherwise, the phase shift will be $e^{-i\Delta t}$ if the parity is even (see Ref. [[1](#ref1)], Sec. 4.7.3). 

This becomes evident after realizing that 

\begin{align*}
Z&=|0\rangle\langle 0|-|1\rangle\langle 1|\\
\implies Z\otimes Z &= (|0\rangle\langle 0|-|1\rangle\langle 1|)\otimes(|0\rangle\langle 0|-|1\rangle\langle 1|)=|00\rangle\langle 00|-|01\rangle\langle 01|-|10\rangle\langle 10|+|11\rangle\langle 11|\\
&=
\begin{bmatrix} 
1 & 0 & 0 & 0 \\ 0 & -1 & 0 & 0 \\ 0 & 0 & -1 & 0 \\ 0 & 0 & 0 & 1  
\end{bmatrix}\\
\implies e^{-itZZ} \equiv e^{-itZ \otimes Z} &=
\begin{bmatrix} 
e^{-it} & 0 & 0 & 0 \\ 0 & e^{it} & 0 & 0 \\ 0 & 0 & e^{it} & 0 \\ 0 & 0 & 0 & e^{-it}  
\end{bmatrix} \\
&= e^{-it}|00\rangle\langle 00| + e^{it}|01\rangle\langle 01| + e^{it}|10\rangle\langle 10| + e^{-it}|11\rangle\langle 11|.
\end{align*}


To verify this result, recall that a Hermitian or Unitary operator $\hat{O}$ is also a Normal operator and, therefore, has a spectral decomposition in terms of the outer product representation in the form $\hat{O} = \sum_j o_j|o_j\rangle \langle o_j|$ according to the spectral decomposition theorem for Normal matrices. In this case, it is possible to write the operator function (matrix function) on a normal matrix as:

$$f(\hat{O})= \sum_j f(o_j) |o_j\rangle \langle o_j|,$$

which is equivalent to (writing $\hat{O} = UDU^{\dagger}$)

\begin{eqnarray}
f(\hat{O}) = Uf(D)U^{\dagger}.
\end{eqnarray}


For the exponential function over the field of the complex numbers, this becomes:

$$ e^{-i\theta\hat{O}} = \sum_{j=1}^n e^{-i\theta o_j} |o_j\rangle \langle o_j| = e^{-i\theta o_1} |o_{1}\rangle \langle o_{1}| + \cdots + e^{-i\theta o_n} |o_{n}\rangle \langle o_{n}|.$$

To see this is true, recall that the eigenvalues of a matrix are multiplied by a scalar when the matrix is multiplied by the same scalar, while the eigenvectors are left unchanged. One can extend this identity to a Kronecker product of Normal operators noting that `the Kronecker product of two Hermitian operators is another Hermitian operator`.

In [86]:
'''Eiganvalues and Eigenvectors of Z.'''

zero=np.array([[1,0]])      # row-like numpy array representing the state |0>.
one=np.array([[0,1]])       # row-like numpy array representing the state |1>.
Z=(zero.T@zero)-(one.T@one) # |0><0| - |1><1|

np.linalg.eig(Z)            # Eigenvalues: +1, -1 | Eigenvectors: |0⟩, |1⟩.

(array([ 1., -1.]),
 array([[1., 0.],
        [0., 1.]]))

In [87]:
'''Eiganvalues and Eigenvectors of ZZ.'''

ZZ = np.kron(Z,Z) # Z⊗Z.

np.linalg.eig(ZZ) # Eigenvalues: +1, -1, -1, +1 | Eigenvectors: |00⟩, |01⟩, |10⟩, |11⟩.

(array([ 1., -1., -1.,  1.]),
 array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]))

**3)** One should recall that $RZ(2t) = e^{-itZ}$.

**Implementing the CNOT gates and the $RZ(2t)$ gate for the parity computation circuit according to steps 2) and 4):**

\begin{eqnarray}
CX^{01}\big(\mathbb{I} \otimes RZ(2t)\big)CX^{01} =
CX^{01}\big(\mathbb{I} \otimes e^{-itZ}\big)CX^{01}\\ 
\end{eqnarray}

Using the equation for a generic CU gate, one can write $CX^{01} = \mathbb{I} \otimes |0\rangle\langle 0\rangle + X \otimes |1 \rangle \langle 1|$. However, in textbook convention this gate reads $CX^{01}=|0\rangle\langle 0|\otimes \mathbb{I} +|1\rangle\langle 1|\otimes X$. One then has:

\begin{eqnarray}
CX^{01}\big(\mathbb{I} \otimes e^{-itZ}\big)CX^{01}=(|0\rangle\langle 0|\otimes \mathbb{I} +|1\rangle\langle 1|\otimes X)\big( \mathbb{I} \otimes e^{-itZ}\big)\big(|0\rangle\langle 0|\otimes \mathbb{I}  +|1\rangle\langle 1|\otimes X \big).
\end{eqnarray}

From here, the distributivity property for matrix product with respect to matrix addition yelds:

$$\big(\mathbb{I}\otimes e^{-itZ}\big)\big(|0\rangle\langle 0|\otimes \mathbb{I} +|1\rangle\langle 1|\otimes X \big) = \big(\mathbb{I}\otimes e^{-itZ}\big) \big(|0\rangle\langle 0|\otimes \mathbb{I} \big) + \big(\mathbb{I} \otimes e^{-itZ}\big)\big(|1\rangle\langle 1|\otimes X \big),$$

Using $(A\otimes B)\cdot(C\otimes D)=A\cdot C\otimes B\cdot D$, the last term becomes:

$$\big(\mathbb{I} \cdot |0\rangle\langle 0|\otimes e^{-itZ} + \mathbb{I} \cdot |1\rangle\langle 1|\otimes e^{-itZ}X \big) = \big(|0\rangle\langle 0|\otimes e^{-itZ} + |1\rangle\langle 1|\otimes e^{-itZ}X \big) .$$ 

The final steps carry on as follows:

\begin{eqnarray}
CX^{01}\big(\mathbb{I}\otimes e^{-itZ}\big)CX^{01} &=& \big(|0\rangle\langle 0|\otimes \mathbb{I} +|1\rangle\langle 1|\otimes X \big)\big(|0\rangle\langle 0|\otimes e^{-itZ} +|1\rangle\langle 1|\otimes e^{-itZ}X \big) \\
&=& |0\rangle\langle 0|\otimes e^{-itZ} +|1\rangle\langle 1|\otimes Xe^{-itZ}X \\ 
&=& |0\rangle\langle 0|\otimes \big(e^{-it}|0\rangle\langle 0|+e^{it}|1\rangle\langle 1|\big) +|1\rangle\langle 1|\otimes X \big(e^{-it}|0\rangle\langle 0|+e^{it}|1\rangle\langle 1|\big)X,
\end{eqnarray}

and noting that $X|0\rangle = |1\rangle$ and $X|1\rangle = |0\rangle$, one gets:

\begin{eqnarray}
CX^{01}\big(\mathbb{I}\otimes e^{-itZ}\big)CX^{01}&=& |0\rangle\langle 0|\otimes \big(e^{-it}|0\rangle\langle 0|+e^{it}|1\rangle\langle 1|\big) +|1\rangle\langle 1|\otimes \big(e^{-it}|1\rangle\langle 1|+e^{it}|0\rangle\langle 0|\big) \\
&=& e^{-it}|00\rangle\langle 00| + e^{it}|01\rangle\langle 01| + e^{it}|10\rangle\langle 10| + e^{-it}|11\rangle\langle 11| \\
&=& e^{-itZZ}.
\end{eqnarray}

## The $e^{-itXX}$ gate

IBM supplementary material provides the following quantum circuit for $e^{-itXX}$:

In [ ]:
# e^{(-itXX)}

'''
from qiskit import QuantumCircuit
from qiskit.circuit import Parameter
'''

t = Parameter('t')
qc = QuantumCircuit(2)
qc.ry(np.pi/2,[0,1])
qc.cnot(0,1)
qc.rz(2 * t, 1)
qc.cnot(0,1)
qc.ry(-np.pi/2,[0,1])

qc.draw()

┌─────────┐                     ┌──────────┐
q_0: ┤ Ry(π/2) ├──■───────────────■──┤ Ry(-π/2) ├
     ├─────────┤┌─┴─┐┌─────────┐┌─┴─┐├──────────┤
q_1: ┤ Ry(π/2) ├┤ X ├┤ Rz(2*t) ├┤ X ├┤ Ry(-π/2) ├
     └─────────┘└───┘└─────────┘└───┘└──────────┘

From the fact that 

$$H|0\rangle = R_y(\pi/2)|0\rangle = \frac{1}{\sqrt{2}}(|0\rangle+|1\rangle) \equiv |+\rangle,$$ 

and 

$$H|1\rangle = R_y(-\pi/2)|0\rangle = \frac{1}{\sqrt{2}}(|0\rangle-|1\rangle) \equiv |-\rangle,$$ 

one equivalent quantum circuit is:

In [ ]:
# Equivalent circuit:

qc = QuantumCircuit(2)
qc.h([0,1])
qc.cx(0, 1)
qc.rz(2 * t, 1)
qc.cx(0, 1)
qc.h([0,1])
qc.draw()

┌───┐                     ┌───┐
q_0: ┤ H ├──■───────────────■──┤ H ├
     ├───┤┌─┴─┐┌─────────┐┌─┴─┐├───┤
q_1: ┤ H ├┤ X ├┤ Rz(2*t) ├┤ X ├┤ H ├
     └───┘└───┘└─────────┘└───┘└───┘

The above circuit can be obtained using the parity trick and a basis change between the Pauli $X$ and $Z$ bases by applying local Hadamard gates on each register. Since the $e^{-itXX}$ gate is not diagonalized in the computational basis (Z-basis), the first pair of Hadamard gates are used to do a basis change (rotation) to the $X$-basis, while the second pair of Hadamard gates change the basis from $X$ back to $Z$ because measurements are made in the Z-basis. The intermediate circuit (the circuit between the Hadamard gates) computes the parity.

**Verification:**



Computing the parity information by acting with the $XX$ operator:


$$XX|++⟩=|++⟩,$$

$$XX|+-⟩=-|+-⟩,$$

$$XX|-+⟩=-|-+⟩,$$

$$XX|--⟩=|--⟩.$$

One should note that $e^{-itXX}$ is shorthand for $e^{-itX \otimes X}.$ From the spectral decomposition theorem for Normal matrices, one has 

$$X = \sum_{j=1}^{d} x_j |x_j \rangle \langle x_j| = |+\rangle\langle +|-|-\rangle\langle -|.$$

Where $$ |\pm\rangle \equiv \frac{1}{\sqrt{2}}(|0\rangle\pm|1\rangle)$$ 

denotes the two orthonormal eigenstates (eigenvectors) of the Pauli $X$-gate according to:

$$X |+\rangle = \frac{1}{\sqrt{2}}(X|0\rangle+X|1\rangle)=\frac{1}{\sqrt{2}}(|1\rangle+|0\rangle)=|+\rangle,$$
$$X |-\rangle = \frac{1}{\sqrt{2}}(X|0\rangle-X|1\rangle) =\frac{1}{\sqrt{2}}(|1\rangle-|0\rangle)=-|-\rangle.$$

With that, one then gets:

\begin{eqnarray}
XX &\equiv& X\otimes X = (|+\rangle\langle +|-|-\rangle\langle -|)\otimes(|+\rangle\langle +|-|-\rangle\langle -|) \tag{1}\\
&=& (|+\rangle\langle +|) \otimes (|+\rangle\langle +|) - (|+\rangle\langle +|) \otimes (|-\rangle\langle -|) - (|-\rangle\langle -|)\otimes (|+\rangle\langle +|) + (|-\rangle\langle -|) \otimes (|-\rangle\langle -|) \tag{2} \\
&=& (|++\rangle\langle ++|)+(|--\rangle\langle --|)-(|+-\rangle\langle +-|)-(|-+\rangle\langle -+|) \tag{3} \\
&\implies & e^{-itX \otimes X} = e^{-it}\bigg(|++\rangle\langle ++|+|--\rangle\langle --|\bigg)+e^{it}\bigg(|+-\rangle\langle +-|+|-+\rangle\langle -+|\bigg) \tag{4}.
\end{eqnarray}

- Eq. (2) was obtained from Eq. (1) using the distributive property:

$$(|a\rangle + |b\rangle)\otimes(|c\rangle + |d\rangle)=|a\rangle \otimes |c\rangle + |a\rangle \otimes |d\rangle + |b\rangle \otimes |c\rangle + |b\rangle \otimes |d\rangle. $$

- Eq. (3) was obtained from Eq. (2) using $(A\otimes B)(C\otimes D)=AC\otimes BD$, or equivalently:

$$|a\rangle \langle c| \otimes |b\rangle \langle d|  = (|a\rangle \otimes |b\rangle)(\langle c| \otimes \langle d|) \doteq |ab\rangle\langle cd|.$$

- Eq. (4) is obtained in the same spirit as the previous problem: either by applying the parity of the state directly, or by using the spectral decomposition theorem for Normal matrices, along with $e^{-i\theta\hat{O}} = \sum_{j=1}^n e^{-i\theta o_j} |o_j\rangle \langle o_j|$. 

Finally, applying a Hadamard gate to change between the $X$ and $Z$ bases ($H|0\rangle = R_y(\pi/2)|0\rangle = |+\rangle$ and $H|1\rangle = R_y(-\pi/2)|0\rangle = |-\rangle$), yields

\begin{eqnarray}
e^{-itX \otimes X} &=& e^{-it}\left[(H\otimes H)|00\rangle\langle 00|(H\otimes H)+(H\otimes H)|11\rangle\langle 11|(H\otimes H)\right]+e^{it}\left[(H\otimes H)|01\rangle\langle 01|(H\otimes H)+(H\otimes H)|10\rangle\langle 10|(H\otimes H)\right] \\
& =& (H\otimes H)\left[e^{-it}(|00\rangle\langle 00|+|11\rangle\langle 11|)+e^{it}(|01\rangle\langle 01|+|10\rangle\langle 10|)\right](H\otimes H) \\
& =& (H\otimes H)e^{-itZ\otimes Z}(H\otimes H) \\
& =& (H\otimes H)C_{x}^{01}\big(\mathbb{I}\otimes e^{-itZ}\big)C_{x}^{01}(H\otimes H) \\
&  =& (H\otimes H)C_{x}^{01}\big(\mathbb{I}\otimes RZ(2t)\big)C_{x}^{01}(H\otimes H).
\end{eqnarray}

**Note**: *some steps have been omitted. I encourage the reader to verify them.*

Specifically, show (algebraically) that:

\begin{eqnarray}
(|a\rangle + |b\rangle)\otimes(|c\rangle + |d\rangle)&=&|a\rangle \otimes |c\rangle + |a\rangle \otimes |d\rangle + |b\rangle \otimes |c\rangle + |b\rangle \otimes |d\rangle, \\
(|a\rangle \langle c|) \otimes (|b\rangle \langle d|)  &=& \big(|a\rangle \otimes |b\rangle\big)\big(\langle c| \otimes \langle d|\big),\\
|++\rangle\langle ++|&=&(H\otimes H)|00\rangle\langle 00|(H\otimes H),\\
|--\rangle\langle --|&=&(H\otimes H)|11\rangle\langle 11|(H\otimes H),\\
|+-\rangle\langle +-|&=&(H\otimes H)|01\rangle\langle 01|(H\otimes H),\\
|-+\rangle\langle -+|&=&(H\otimes H)|10\rangle\langle 10|(H\otimes H),\\
\end{eqnarray}

You can open a pool request to share your contribution.

<div class="alert alert-block alert-info">
<b>Eigenvalues\Eigenvectors of X and XX</b>. 
</div>

In [55]:
'''Eiganvalues and Eigenvectors of X.'''

#Note: the eigenvalues of the printed numpy.ndarray are not necessarily ordered.

plus=1/(np.sqrt(2))*(zero+one)      # 1/[sqrt(2)](|0> + |1>).
minus=1/(np.sqrt(2))*(zero-one)     # 1/[sqrt(2)](|0> - |1>).
X=(plus.T@plus)-(minus.T@minus)     # |+><+|-|-><-|

np.linalg.eig(X)                    # Eigenvalues: +1, -1 | Eigenvectors: |+⟩, |-⟩.

(array([ 1., -1.]),
 array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

In [71]:
'''Eiganvalues and Eigenvectors of XX.'''

XX = np.kron(X,X) # X⊗X.

np.linalg.eig(XX) # Eigenvalues: +1, -1, +1, -1.

(array([ 1., -1.,  1., -1.]),
 array([[ 0.70710678,  0.70710678,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.70710678, -0.70710678],
        [ 0.        ,  0.        ,  0.70710678,  0.70710678],
        [ 0.70710678, -0.70710678, -0.        ,  0.        ]]))

$$XX|++⟩=|++⟩$$

In [74]:
np.kron(plus.T,plus.T) # |++⟩

array([[0.5],
       [0.5],
       [0.5],
       [0.5]])

In [75]:
XX@(np.kron(plus.T,plus.T)) # 𝑋𝑋|++⟩=|++⟩

array([[0.5],
       [0.5],
       [0.5],
       [0.5]])

$$XX|+-⟩=-|+-⟩$$

In [76]:
np.kron(plus.T,minus.T) # |+−⟩

array([[ 0.5],
       [-0.5],
       [ 0.5],
       [-0.5]])

In [77]:
XX@(np.kron(plus.T,minus.T)) # 𝑋𝑋|+−⟩=−|+−⟩

array([[-0.5],
       [ 0.5],
       [-0.5],
       [ 0.5]])

$$XX|-+⟩=-|-+⟩$$

In [80]:
np.kron(minus.T,plus.T) # |−+⟩

array([[ 0.5],
       [ 0.5],
       [-0.5],
       [-0.5]])

In [81]:
XX@(np.kron(minus.T,plus.T)) # 𝑋𝑋|−+⟩=−|−+⟩

array([[-0.5],
       [-0.5],
       [ 0.5],
       [ 0.5]])

$$XX|--⟩=|--⟩$$

In [84]:
np.kron(minus.T,minus.T) # |−−⟩

array([[ 0.5],
       [-0.5],
       [-0.5],
       [ 0.5]])

In [85]:
XX@(np.kron(minus.T,minus.T)) # 𝑋𝑋|−−⟩=|−−⟩

array([[ 0.5],
       [-0.5],
       [-0.5],
       [ 0.5]])

<div class="alert alert-block alert-info">
<b>Identities:</b> verifying some of the above identities using <b>NumPy</b>. 
</div>

$$XX \equiv X\otimes X :$$

In [57]:
XX

array([[0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.]])

$$XX \equiv X\otimes X = (|+\rangle\langle +|-|-\rangle\langle -|)\otimes(|+\rangle\langle +|-|-\rangle\langle -|):$$

In [45]:
np.kron((plus.T@plus)-(minus.T@minus), (plus.T@plus)-(minus.T@minus))

array([[0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.]])

$$XX \equiv X\otimes X = (|+\rangle\langle +|) \otimes (|+\rangle\langle +|) - (|+\rangle\langle +|) \otimes (|-\rangle\langle -|) - (|-\rangle\langle -|)\otimes (|+\rangle\langle +|) + (|-\rangle\langle -|) \otimes (|-\rangle\langle -|):$$

In [46]:
np.kron((plus.T@plus),(plus.T@plus))-np.kron((plus.T@plus),(minus.T@minus))-np.kron((minus.T@minus),(plus.T@plus))+np.kron((minus.T@minus),(minus.T@minus))

array([[0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.]])

$$XX \equiv X\otimes X =(|++\rangle\langle ++|)+(|--\rangle\langle --|)-(|+-\rangle\langle +-|)-(|-+\rangle\langle -+|)$$

In [48]:
(np.kron(plus.T,plus.T)@np.kron(plus,plus))+(np.kron(minus.T,minus.T)@np.kron(minus,minus))-(np.kron(plus.T,minus.T)@np.kron(plus,minus))-(np.kron(minus.T,plus.T)@np.kron(minus,plus))

array([[0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.]])

## The $e^{-itYY}$ gate

IBM supplementary material provides the following quantum circuit for $e^{-itYY}$:

In [ ]:
# e^{(-itZZ)}

'''
from qiskit import QuantumCircuit
from qiskit.circuit import Parameter
'''

t = Parameter('t')
qc = QuantumCircuit(2)
qc.rx(np.pi/2,[0,1])
qc.cnot(0,1)
qc.rz(2 * t, 1)
qc.cnot(0,1)
qc.rx(-np.pi/2,[0,1])

qc.draw()

┌─────────┐                     ┌──────────┐
q_0: ┤ Rx(π/2) ├──■───────────────■──┤ Rx(-π/2) ├
     ├─────────┤┌─┴─┐┌─────────┐┌─┴─┐├──────────┤
q_1: ┤ Rx(π/2) ├┤ X ├┤ Rz(2*t) ├┤ X ├┤ Rx(-π/2) ├
     └─────────┘└───┘└─────────┘└───┘└──────────┘

From the fact that 

$$SH|0\rangle = R_x(-\pi/2)|0\rangle = \frac{1}{\sqrt{2}}(|0\rangle+i|1\rangle) \equiv |\oplus\rangle,$$ 

and 

$$SH|1\rangle = R_x(\pi/2)|0\rangle = \frac{1}{\sqrt{2}}(|0\rangle-i|1\rangle) \equiv |\ominus\rangle,$$ 

one equivalent quantum circuit is:

In [ ]:
# Equivalent circuit:

qc = QuantumCircuit(2)
qc.sdg([0,1])
qc.h([0,1])
qc.cx(0, 1)
qc.rz(2 * t, 1)
qc.cx(0, 1)
qc.h([0,1])
qc.s([0,1])
qc.draw()

┌─────┐┌───┐                     ┌───┐┌───┐
q_0: ┤ Sdg ├┤ H ├──■───────────────■──┤ H ├┤ S ├
     ├─────┤├───┤┌─┴─┐┌─────────┐┌─┴─┐├───┤├───┤
q_1: ┤ Sdg ├┤ H ├┤ X ├┤ Rz(2*t) ├┤ X ├┤ H ├┤ S ├
     └─────┘└───┘└───┘└─────────┘└───┘└───┘└───┘

**Verification:**


One should note that $e^{-itYY}$ is shorthand for $e^{-itY \otimes Y}$. Following a similar thought process as before, one writes the Pauli operator $Y$ in the basis of its eigenvectors:

$$Y=|\oplus\rangle\langle \oplus|-|\ominus\rangle\langle \ominus|,$$

where

$$|+y\rangle \equiv |\oplus\rangle = \frac{1}{\sqrt{2}}(|0\rangle+i|1\rangle) \text{ and } |-y\rangle \equiv |\ominus\rangle = \frac{1}{\sqrt{2}}(|0\rangle-i|1\rangle).$$

Therefore,

\begin{eqnarray}
YY &\equiv& Y \otimes Y = (|\oplus\oplus\rangle\langle \oplus\oplus|+|\ominus\ominus\rangle\langle \ominus\ominus|)-(|\oplus\ominus\rangle\langle \oplus\ominus|+|\ominus\oplus\rangle\langle \ominus\oplus|) \\
&\implies& e^{-itY\otimes Y} = e^{-it}(|\oplus\oplus\rangle\langle \oplus\oplus|+|\ominus\ominus\rangle\langle \ominus\ominus|) + e^{it}(|\oplus\ominus\rangle\langle \oplus\ominus|+|\ominus\oplus\rangle\langle \ominus\oplus|).
\end{eqnarray}

The next step is to apply a basis change, as follows:

$$|\oplus\rangle = SH|0\rangle = R_x(-\pi/2)|0\rangle  \text{ and }  |\ominus\rangle = SH|1\rangle = R_x(\pi/2)|0\rangle,$$

such that

\begin{align}
e^{-itY\otimes Y} & = (S\otimes S)(H\otimes H)\Big(e^{-it}(|00\rangle\langle 00|+|11\rangle\langle 11|)+e^{it}(|01\rangle\langle 01|+|10\rangle\langle 10|)\Big)(H\otimes H)(S^{\dagger}\otimes S^{\dagger}) \\
& = (S\otimes S)(H\otimes H)e^{-itZ \otimes Z}(H\otimes H)(S^{\dagger}\otimes S^{\dagger}) \\
& = (S\otimes S)e^{-itX\otimes X}(S^{\dagger}\otimes S^{\dagger}) \\
& = (S\otimes S)(H\otimes H)C_{x}^{01}\big(\mathbb{I}\otimes e^{-itZ}\big)C_{x}^{01}(H\otimes H)(S^{\dagger}\otimes S^{\dagger}) \\
& = (S\otimes S)(H\otimes H)C_{x}^{01}\big(\mathbb{I}\otimes RZ(2t)\big)C_{x}^{01}(H\otimes H)(S^{\dagger}\otimes S^{\dagger}).
\end{align}

Note that 

$$(SHCX)^{\dagger} = (CX)^{\dagger}(SH)^{\dagger} = (CX)H^{\dagger}S^{\dagger} = CXHS^{\dagger},$$ 

$$[(S\otimes S)(H\otimes H)CX]^{\dagger} = [(H\otimes H)CX]^{\dagger}(S\otimes S)^{\dagger}= (CX)^{\dagger}(H\otimes H)^{\dagger}(S\otimes S)^{\dagger} = CX (H\otimes H) (S^{\dagger} \otimes S^{\dagger}),$$

where it was used identities $(AB)^{\dagger}=B^{\dagger}A^{\dagger}$ and $(A \otimes B)^{\dagger}=A^{\dagger} \otimes B^{\dagger}$.

This can be verified using qiskit.opflow:

In [25]:
from qiskit.opflow import S, H, CX, I

SS = S.tensor(S)
HH = H.tensor(H)
SSdagg=S.adjoint().tensor(S.adjoint())

(S@H@CX).adjoint() == (CX@H@S.adjoint()), (SS@HH@CX).adjoint() == (CX@HH@SSdagg)

(True, True)

Such that 

$$ SHCXCXHS^{\dagger}= \mathbb{I},$$

$$ (S\otimes S) (H\otimes H)CXCX(H\otimes H)(S^{\dagger}  \otimes S^{\dagger})= \mathbb{I},$$

which can also be verified using qiskit.opflow:

In [44]:
(S@H@CX@CX@H@S.adjoint()).to_matrix()

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j]])

In [45]:
((SS)@(HH)@CX@CX@(HH)@(SSdagg)).to_matrix()

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j]])

In [46]:
(I.tensor(I)).to_matrix()

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j]])

# State Fidelity<a name="fid" />  

In noisy environments, the evolved quantum state must be represented by a mixed density operator. The fidelity between two mixed density operators (density matrices) $\rho$ and $\sigma$ is:

\begin{align}
F(\rho,\sigma) = \left(tr \sqrt{\rho^{1/2} \sigma \rho^{1/2}}\right)^2,
\end{align}

with $\rho= p_j\sum_j|\psi_{j}\rangle \langle \psi_{j}|$ and $\sigma=p_k\sum_k|\psi_{k}\rangle \langle \psi_{k}|$, where $p_j$ and $p_k$ are the corresponding (eigenvalue) probability distributions.

If one of the states is a pure state ($\rho=|\psi_{\rho}\rangle \langle \psi_{\rho}|$), the above result boils down to the fidelity between a pure and a mixed state:

\begin{align}
F(\sigma, |\psi_{\rho}\rangle) = \langle\psi_{\rho}|\sigma|\psi_{\rho}\rangle = \sum_{j,k=0}^{d-1}\psi_{j}^{*}\sigma_{j,k}\psi_{k}.
\end{align}

In a noise-free environment, both the evolved state and the target states are pure states, the state fidelity thus becomes:

\begin{align}
F(\rho, \sigma) = |\langle\psi_{\rho}|\psi_{\sigma}\rangle|^2.
\end{align}

# &nbsp; <a href="#"><img valign="middle" height="45px" src="https://img.icons8.com/book" width="45" hspace="0px" vspace="0px"></a> References<a name="ref" />

\[1] Nielsen MA, Chuang IL. 2010. Quantum Computation and Quantum Information. New York: [Cambridge Univ. Press.](https://doi.org/10.1017/CBO9780511976667) 10th Anniv. Ed.<a name="ref1" />  
- Corollary 4.2, pg. 176: Gate decomposition.
- Theorem 4.3, pg. 207: Trotter formula. 
- Chapter 4.7.2, pg. 206: The quantum simulation algorithm. 
- Chapter 9.2.2, pg. 409: State fidelity.
  
\[2] Griffiths, David J., and Darrell F. Schroeter. Introduction to quantum mechanics. Cambridge University Press, 2018.
- Section 3.2.3, pg. 103: scalar wave function.

\[3] [ibmq-qsim-challenge.ipynb](https://github.com/qiskit-community/open-science-prize-2021/blob/main/ibmq-qsim-challenge.ipynb).

\[4] [ibmq-qsim-sup-mat.ipynb](https://github.com/qiskit-community/open-science-prize-2021/blob/main/ibmq-qsim-sup-mat.ipynb).

\[5] [YQIS 6 Invited 8: Yuan Su, Trotterization and Trotter error](https://www.youtube.com/watch?v=KPofFJc57gU).<a name="ref5" />  

\[6] [Quantum Algorithms for Hamiltonian Simulation | Quantum Colloquium](https://www.youtube.com/watch?v=X4gegxIuh1o).<a name="ref6" />  